### ISSUE TITLE
Stackable bottom edge with finger joints

### ISSUE THREAD

**Issue by Blancanegra** [florianfesti/boxes#111]
Actually there are no finger joints along the bottom edges "s" and "h"" below holes of FingerHoleEdge.
Extending the edge type to the end would make the legs stronger even for low "s" and "h" edge heights.

![stackable edge](https://user-images.githubusercontent.com/32768345/51379032-c92a5e80-1b0e-11e9-945e-79ce3518df73.jpg)
Top figure: actual stackable edge.
Bottom figure: proposed edge fix.

**Comment by florianfesti** [comment]
This is a bit more tricky than it looks.
I have to think a bit to figure out how to do this. The issue here is that the height of the wall is distance from the top edge to the top of the finger holes. This way a adjacent wall of the same height fits there if it has a "f" edge on the side - no matter what top or bottom edge it has. Extending the side edge down to the floor requires adjusting some sizes and breaks the compatibility between all bottom edge types (F, h, s).
This can be done for some generators but not for arbitrary walls.

**Comment by florianfesti** [comment]
Ok, turns out adding `ignore_widths=[1, 6]` to the side walls does just this. Now I just need to modify all generators that make use if h and s edges or the bottom_edge param...

**Comment by Blancanegra** [comment]
Great!
Thank you.
