### ISSUE TITLE
Paintstorage - Wrong height in bottom piece

### ISSUE THREAD

**Issue by Blancanegra** [florianfesti/boxes#133]
The height of the small pieces at the bottom is proportionally less than (holedistance) + (feetheight), is there any reason for that or is just a bug?

**Comment by florianfesti** [comment]
Yes and Yes.
The reason is to not touch the ground with this part. The stackable edge creates these feet that makes it easier for the "box" to stand on uneven ground.
The implementation could probably be better. May be even following the contour of the bottom edge of the side wall. I'll look into it.

**Comment by Blancanegra** [comment]
Watching the code it's 0.8 in height. 
It's OK to me, but store paint cans on an unneven ground is not a good idea! ;)
