### ISSUE TITLE
Generator "OttoBody" broken since introduction of class "HexHolesSettings"

### ISSUE THREAD

**Issue by ottobot42** [florianfesti/boxes#250]
With commit e643e07b4d6720dfbe18400a2d29ae197f71b3d1 the class "HexHolesSettings" has been introduced in "boxes/__init__.py" but in "boxes/generators/ottobody.py" line 45 a tuple is passed to the method "hexHolesCircle()" which then calls "hexHolesRectangle()". Here data is retrieved from the class "HexHolesSettings" while a tuple  was passed into "hexHolesRectangle()".

**Comment by florianfesti** [comment]
Sorry! This took much longer than it should have. But for some reason I took a wrong turn the first time trying to fix this. Turns out when doing the right thing it is as simple a fix as expected.
There is probably more stuff wrong with the hex holes code, but that's unrelated to this issue. I hope this does works for you now.

Thanks for reporting!
