### ISSUE TITLE
Make outer edge continuous

### ISSUE THREAD

**Issue by florianfesti** [florianfesti/boxes#29]
even if other parts are drawn intermediately.

It's still unclear if thit can be done with cairo. Further examination is needed. May be draw on separate groups or canvases during callbacks.

**Comment by dshookowsky** [comment]
![laserpath](https://user-images.githubusercontent.com/970386/28748382-5926c0ec-7484-11e7-9051-832b236381c3.png)
![doc](https://user-images.githubusercontent.com/970386/28748383-5c1b1f8c-7484-11e7-981b-ecced8caa38b.png)

I think this is affecting me when I try to use the output with laserweb.  It's skipping part of the path and almost looks like it's joining different shapes

**Comment by florianfesti** [comment]
Looks like this might be possible to fix using the RecordingSurface. Unfortunately is is only available in pretty recent cairo versions and is still buggy. While I could make it work with the PDFSurface it failed miserably with the SVGSurface.
I was playing with the RecordingSurface to get a sane way of determining the size of the drawing and to enable the built-in PDF back end.

**Comment by Mumeii** [comment]
On my side i only use boxes.py thanks the web interface, save the produced svg file and load it with inkscape. Doing so I've indeed noticed that produced boxes outer frames are not continuous due to strange inkscape behaviour while performing union, division or such path operations on produced boxe's paths

Having a deeper look at it, I've noticed that Inkscape perform path formulas optimizations, like for example `v 0` useless shortcut or `m 0 0` relative useless moves, that split the path apart

I guess the root cause is unoptimized path formulas produced by Cairo such as ::

`... L 5.5 0 M 5.5 0 ...` (pencil useless move)

fixing them with a regular expression by removing the useless Move operation lead to further possible optimisations on things such as ::

`... C 1 2 3 4 L 3 4 ...` (blank line drawing)

So right now i'm using the following quick fix as i'm definitely not familiar with either Python or Cairo. I apply twice the following regular expression replacement on the produced file ::

`(\-?\d+(\.\d+)?) (\-?\d+(\.\d+)?) (M|C|L) \1 \3` replaced with `$1 $3`

Hope it can help a bit and you could patch the code and the website in a near future ;)

**Comment by florianfesti** [comment]
Path is now optimized by removing unnecessary moves (#63).
Still need to check whether the path gets interrupted by callbacks. May be the pieces can be stitched together by looking for paths with matching end and start point.

**Comment by florianfesti** [comment]
OK, the new back end (see #192) this should be solved. It indeed could not be done with Cairo.

Closing.
