### ISSUE TITLE
A PaperBox that needs less paper

### ISSUE THREAD

**Issue by fuddl** [florianfesti/boxes#351]
I tried to recreate a chocolate box with the dimensions 85×84×13 mm. Unfolded, this  box could be made out of a sheet of 133×199 mm.

![an unfolded paper box](https://user-images.githubusercontent.com/842548/146583615-21803321-4629-4379-bc9c-cb6a4cc7f5fc.png)

If I generate a PaperBox [with the same dimensions](https://festi.info/boxes.py/PaperBox?x=84&y=13&h=85&lid_heigth=15&lid_radius=7&lid_sides=20&margin=0.5&mark_length=1.5&tab_angle_rad=0.07982998571223732&finger_hole_diameter=15&thickness=3.0&format=svg&tabs=0.0&debug=0&labels=0&labels=1&reference=100&burn=0.1&render=1) it needs sheet of 213×294 mm with a lot of paper to throw away after. Also if scaled up, it exceeds the maximum paper size of my plotter. 😅

I propose a more space efficient PaperBox design based on my chocolate box.

Box                   | sheet size needed
---------------|---------------------
PaperBox         | 62 622mm²
[new design]  | 26 467mm²

The new design requires 42.26% less paper. Is it a good idea? Is that something worth looking into?

**Comment by gcollic** [comment]
Hello !

I'm the original contributor of this paper box. Here is my opinion ;-)

Is the original paper box like you want if you exchange y and h ? https://festi.info/boxes.py/PaperBox?x=84&y=85&h=13&lid_heigth=15&lid_radius=7&lid_sides=20&margin=0.5&mark_length=1.5&tab_angle_rad=0.07982998571223732&finger_hole_diameter=15&thickness=3.0&format=svg&tabs=0.0&debug=0&labels=0&labels=1&reference=100&burn=0.1&render=1

Your box is similar but doesn't look identical.The current box was created for advent calendar cases, it's not clear if I can use your design for this purpose without some tradeoff, and I wonder if your design is more efficient with any parameters combination (in paper size, but also folding simplicity, and opening ergonomy).

I think having both could maybe be interesting. I'm not sure if it would be better as a whole new box or as a simple "design type" parameter for the current box. In both cases, we could think collectively of how to name both so that the difference makes sense ;-)

**Comment by gcollic** [comment]
On the sample I linked with y and h switched, I'm happy with the "tabs" which takes half of the length of the box, so that they are touching each others when folded, since it doubles the thickness of the paper when glued, but if this sample is similar to your target maybe the tab length is the missing parameter we could add to optimize in your case ?

**Comment by fuddl** [comment]
hi, @gcollic thanks for your quick feedback.

> Is the original paper box like you want if you exchange y and h?

Not quite, the important feature of the chocolate box (which I forget to mention) is that it opens on the narrowest side, rather then the _top_ side. It is also designed to be unglued on the tabs since they are part of the opening mechanism:

![a box that opens on it's smallest edge](https://user-images.githubusercontent.com/842548/146639692-1e68d589-435c-49d2-8a94-60a2abfacef5.png)

I think  [on the image above](#issue-1083486287) it's clear where the glue used to be.

I propose to rename the parameters (or rather the labels of the input fields) to make more clear which side the lid is. Or provide some clues like a sketch:

![A bot where each edge is labeled X, Y or H](https://user-images.githubusercontent.com/842548/146640496-7e6f5eff-6d99-4e98-ab7f-624295ed20d5.png)

> maybe the tab length is the missing parameter we could add to optimize in your case ?

Yes, that sounds great.

**Comment by fuddl** [comment]
The other parameter seems to be: are the tabs supposed to be glued or are they part of the lid mechanism?

![Group 4](https://user-images.githubusercontent.com/842548/146640705-f3a40a27-b684-48f1-ac23-0c6bb42ddbf4.png)

**Comment by gcollic** [comment]
Thank you for all the explanations, I think I understand better.

Your box have 2 lids on the narrowest side without cutout for the finger (but I suppose it could), when mine has only one on the top side with a cutout for the finger.

Both have tabs to be glued : 4 glued against walls in my design like your right diagram, 2 glued to each others in yours (not visible in your diagrams).

Both have tabs that are part of the opening mechanism (2 for each lid), so both our box are like your left diagram.

I think it's a totally different design, but I'm still not sure if a second box or a "design type" option makes more sense.

If they are different boxes, maybe a "flat paper box" and a "regular paper box" ?

I'm wondering if @florianfesti has an opinion on the subject ^^

**Comment by gcollic** [comment]
>provide some clues like a sketch

I love your sketches by the way! Very clear!

**Comment by florianfesti** [comment]
I don't have a strong opinion on the subject. My initial instinct was that having variant in the same generator is probably better UI wise. But that might just be me being bad with generator names and not being too much interested in paper boxes in the first place. So I am fine with both approaches. Having separate generator may make it easier to start an Paper group if more paper based generators emerge.

**Comment by gcollic** [comment]
Thank you @florianfesti :-)

@fuddl are the following differences right and comprehensive? (black = original only, red = new only, green = both)
![image](https://user-images.githubusercontent.com/763200/146671561-669c10df-3131-4108-b387-d9a2917a0f07.png)


There is a lot of differences, but parameters could all be the same (dimensions, optional round cut for thumbs, tabs length, etc.).
I think I would keep a single box with a parameter for the kind of box (top box and tuck box ?). And in the `render` method I would directly switch between two render sub-methods dedicated to each kind, reusing the same parameters and helper methods (finger_hole, etc.).

What do you think ?

PS: I think I will use your design for other purposes also, such as game cards tuck box ^^

**Comment by fuddl** [comment]
This looks great and comprehensive. I would personally not need a second lid → only one of the openings needs a thumb cut.

I like the single parameter approach but it should be made clear what the parameter does. I'd be happy to provide explanatory sketches if you want.

Also I'm  curious to see, the diff in the code, if you decide to implement it.

**Comment by florianfesti** [comment]
Guess this is done! Should have added a "Resolved" line to the commit message.
