### ISSUE TITLE
DividerTray - last compartment

### ISSUE THREAD

**Issue by tomse** [florianfesti/boxes#374]
Is it possible to have the last angled compartment splitter as close to the back wall as possible.
just like the picture here
https://www.festi.info/boxes.py/DividerTray?language=en

here is the result of my setup, and it's a little difficult to fish up the last item.

![IMG_20220320_235306_](https://user-images.githubusercontent.com/1444539/159189596-e8ba4977-390e-4cdd-b8b3-4dd0f2d5a25b.jpg)

A full width splitter could be useful as well, as you can see in the same pic.
being far from a python dev, I could try and code this splitter, but please bear with me here.

**Comment by gcollic** [comment]
Hello :-)

I contributed this box.

> Is it possible to have the last angled compartment splitter as close to the back wall as possible

Yes, it's already possible. It's a section parameter also used in other boxes, there is a link next to it with [more documentation](https://florianfesti.github.io/boxes/html/usermanual.html#section-parameters). Instead of "3*50", you can try "0:3*50:0", and the first and last sections will be of size "0", meaning against the wall.

> A full width splitter could be useful

It's a good idea for some cases! I don't have the time right now to add this option myself, but I could look into it someday if it can wait.

**Comment by tomse** [comment]
Nice thank you! :-D 

There is no rush. They are easy to combine by hand

And thank you for contributing this box. It's much appreciated :-D

**Comment by AllanKustom** [comment]
How do you get the extra slots in please ? 
Your creation looks great its similar to what I'm trying to make.

**Comment by florianfesti** [comment]
Ok, these patches should fix these issues. They are still untested and not on the web instance yet. @tomse can you try them out and report back if everything looks fine, please?

**Comment by tomse** [comment]
wow.. that was fast. I'll see if I can find time to test it soon (hopefully tonight)

**Comment by tomse** [comment]
@florianfesti just tested it.. and result is great. thanks a lot!
I also tested with @gcollic 's suggestion. Which also seems to work wonders. Loving it :-D 

it would be helpful with some help text for gcollic's suggestion,

**Comment by florianfesti** [comment]
Actually the "0:" trick is now mentioned in the description text which is displayed below the setting dialog.

**Comment by tomse** [comment]
so it is, I missed that :-D  thanks again
