### ISSUE TITLE
UniversalBox has no argument `outside`

### ISSUE THREAD

**Issue by Rotzbua** [florianfesti/boxes#82]
Is there a reason?

**Comment by florianfesti** [comment]
Well, yes there is.

CLOSED WONTFIX.






Ok, just kidding. The issue with UniversalBox is the universal part. It is not that clear what outside means. Should the size of the box change depending on the edge types selected at top and bottom? Do you measure from the top of the box or the top of the lid or the top of the hinges. Same question for hinges sticking out on the back. 
What if you select a chest lid? Should that count to the height?

I probably just could make a decision on how each of these things are treated. But that would probably confuse most users even more than they would be helped by the switch. That's why it has not been added. If you have a good - and unambiguous - way of adding the parameter I am all for it. May be choosing a very simple way and having more than the typical explanation text can solve the issue.
